name: conquest_functions
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  async: ^2.11.0
  lints: ^2.0.0
  test: ^1.24.7
