name: udp_client
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <5.0.0'

# Add regular dependencies here.
dependencies:
  protocol:
    # Настройки пакета
    path: ../protocol

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
