name: json_store
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <5.0.0'

dependencies:
  path: ^1.8.3
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
