name: macros_first_blood
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.0-278.0.dev

dependencies:
  json: ^0.20.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
