name: my_new_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  mad_package:
    git: https://github.com/MADTeacher/mad_package.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
