name: packeges_test
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# устанавливаем зависимости проекта
dependencies:
  library_test: # имя подключаемого пакета
    path: ../library_test

dev_dependencies:
  pedantic: ^1.9.0
