name: mad_package
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
repository: https://github.com/MADTeacher/mad_package

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
