name: my_app
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.2

# Устанавливаем зависимости проекта
dependencies:
  #На этом уровне имена подключаемых пакетов
  mad_package:
    # Настройки пакета
    path: ../mad_package

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
