name: macro_function
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-278.0.dev

# Add regular dependencies here.
dependencies:
  macros: ^0.1.2-main.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
