name: NativeLibrary # имя генерируемого класса
description: Bindings to `src/lib_func.h`.
output: 'lib/ffi_gen.dart' # генерируемый файл
headers:
  entry-points: # расположение заголовочных файлов
    - 'src/lib_func.h'
