name: students_server
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.3
  mockito: ^5.0.7
  build_runner: ^2.0.2
